config/routes.rb
Tb::Application.routes.draw do



  resources :travels, :only => [:new, :create] do
    collection do
      get 'match'
    end
  end

  resources :trips, :except => [:destroy, :edit] do
    member do
      get  'invite_friends', :as => 'invite_users'
      post 'invite_friends'
      put  'join'
      put  'leave'
      put  'reject'
      put  'accept'
    end
    resources :files, :except => [:show, :index, :edit, :update]
    resources :events, :except => [:show, :index]
  end
  match '/trips/:id/:year(/:month)' => 'trips#show', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/trips/:trip_id/user/:id/accept' => 'trips#accept_user', :as => :accept_user_trip, :via => :put
  match '/trips/:trip_id/user/:id/deny' => 'trips#deny_user', :as => :deny_user_trip, :via => :put

  root :to => "main#index"

  match "/signin" => "services#signin"
  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      get 'failure'
    end
  end

  match 'user/settings' => 'main#user_settings', :as => 'user_settings'
  match 'user/:uid' => 'main#user_profile', :as => 'user_profile'
  match 'friend/facebook/:uid' => 'facebook#friend_info'
  match 'other-facebook-friends' => 'facebook#not_in_app_friends'

  match 'message/:id' => 'main#message'

  match 'invite_friends' => 'facebook#invite', :as => 'invite_friends'
  match 'share' => 'facebook#share', :as => 'share'

  match 'welcome' => 'facebook#welcome'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  include Upload

  # regular users in the group
  has_and_belongs_to_many :users, :uniq => true
  # users not approved to be in the group
  has_and_belongs_to_many :waitings, :uniq => true, :class_name => 'User', :association_foreign_key => "waiting_id", :join_table => 'trips_waitings'
  # users not approved to be in the group
  has_and_belongs_to_many :invitees, :uniq => true, :class_name => 'User', :association_foreign_key => "invitee_id", :join_table => 'trips_invitees'

  has_many :travels

  has_many :events
  has_many :attachments

  attr_accessible :name, :about, :travels_attributes

  validates_presence_of :name

  accepts_nested_attributes_for :travels, :reject_if => :all_blank, :allow_destroy => true

  # create map from svg data and upload to s3
  def map=(svg)
    svg_to_img_to_s3 "tripmap/#{self.id}.jpg", svg
    map # return value is map, see below
#  rescue
#    map
  end
  # map (as image on s3) link
  def map
    t = Time.now.to_i # always load new
    "http://#{AppConfig.s3.bucket}.s3.amazonaws.com/tripmap/#{self.id}.jpg?t=#{t}"
  end


  def pals_of(user)
    self.users - [user]
  end

  def invite_users_with_facebook_ids(uids)
    users = User.where(:facebook_id => uids).select('distinct users.*')
    users.each do |user|
      next if self.users.include?(user) or self.invitees.include?(user) or self.waitings.include?(user)
      self.invitees << user
      # send notification to this user
      if user.notify_throught_wall?
        message = "#{I18n.t('invitation_feed_message') } #{self.name}"
        user.facebook_put_feed(I18n.t('invitation_mail_subject'), message)
      elsif user.notify_throught_mail?
        NoticeMailer.delay.trip_invitation(user, self)
      end
    end
    true
  end

  def save_request(user)
    return false if self.users.include?(user) or self.invitees.include?(user) or self.waitings.include?(user)
    # save him in DB
    self.waitings << user
    # send notification to all group members
    self.users.each do |user|
      if user.notify_throught_wall?
        message = "#{I18n.t('request_feed_message') } #{self.name}"
        user.facebook_put_feed(I18n.t('request_mail_subject'), message)
      elsif user.notify_throught_mail?
        NoticeMailer.delay.trip_request(user, self)
      end
    end
    true
  end

  # it is case of countries.size (count)
  def message_country
    countries = self.travels.country
    return nil if countries.blank?
    n = AppConfig.shown_countries
    if countries.size == 1
      ctext = countries.first.countryname
    elsif countries.size == 2
      ctext = "#{countries.first.countryname} and #{countries.last.countryname}"
    elsif countries.size <= n
      ctext = countries[0..-2].map {|c| c.countryname }.join(', ')
      ctext << " and #{countries.last.countryname}"
    elsif countries.size == n + 1
      ctext = countries[0..(n-1)].map {|c| c.countryname }.join(', ')
      ctext << " and #{countries.last.countryname}"
    elsif countries.size > n
      ctext = countries[0..(n-1)].map {|c| c.countryname }.join(', ')
      alt = countries[n..-2].map  {|c| c.countryname }.join(', ')
      alt << " and #{countries.last.countryname}"
      ctext << " and <a name=\"c\" title=\"#{alt}\">#{countries.size - n} other countries</a>"
    end
    ctext
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_filter :authenticate_user!

  def show
    @countries   = []
    @preferences = []
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i
    @shown_month = Date.civil(@year, @month)
    # load travel preferences and show them
    unless @trip = Trip.find(params[:id])
      redirect_to '/404.html'
      return
    end
    if @user_own_trip = @trip.users.include?(current_user)
      @files = @trip.attachments
    end
    @user_invited_trip = @trip.invitees.include?(current_user)
    @user_waiting_trip = @trip.waitings.include?(current_user)

    @country_message = @trip.message_country
    @active_tab = flash[:anchor] ? flash[:anchor].to_sym : nil

    i = 0
    @trip.travels.each do |travel|
      if travel.country.blank?
        @preferences.push travel
        @trip.events.build({  color: Event::PREFERENCES_COLORS[i],
          start_at: travel.begins, end_at: travel.ends, name: "#{(i+=1).ordinalize} preference"
        })
      else
        @countries.push travel.country
      end
    end
    # methods defined by Calendar_Event gem
    start_d, end_d = Event.get_start_and_end_dates(@shown_month)
    @event_strips  = Event.create_event_strips(start_d, end_d, @trip.events)
    @users = @trip.users
  end

  def new
    @countries   = []
    @preferences = []
    @trip = current_user.trips.build
  end

  def create
    @existing_countries = []
    @trip = current_user.trips.create(travels_attributes.merge(params[:trip]))
    if not @trip.errors.any?
      @trip.map = params[:map]

      # make message to Friend updates; helper method here
      country_message = @trip.message_country
      current_user.make_message(
        "created new trip group #{view_context.link_to @trip.name, trip_path(@trip)} to #{country_message}"
      )

      flash[:success] = t('create_trip_success')
      redirect_to trip_path(@trip)
    else
      # invalid attributes - transform them to show
      @countries = params[:countries]||[].collect {|c|c.first}
      @preferences = params[:preference].values.map do |preference|
        OpenStruct.new(preference) # hash with method-like access
      end
      @error = t('create_trip_error') +' '+ @trip.errors.full_messages.join('. ')
      render :action => 'new'
    end
  end

  def update
    unless @trip = current_user.trips.find(params[:id])
      redirect_to '/404.html'
      return
    end
    @existing_countries = @trip.travels.country
    if @trip.update_attributes(travels_attributes.merge(params[:trip]))
      @trip.map = params[:map]
      flash[:success] = t('update_trip_success')
      redirect_to trip_path(@trip)
    else
      # invalid attributes - transform them to show
      @countries = params[:countries].collect {|c|c.first}||[]
      @preferences = params[:preference].values.map do |preference|
        OpenStruct.new(preference) # hash with method-like access
      end
      @error = t('update_trip_error')
      render :action => 'edit'
    end
  end

  # invitation form and his post action
  def invite_friends
    unless @trip = current_user.trips.find(params[:id])
      redirect_to '/404.html'
      return
    end
    if request.post?
      if params[:users] =~ /(\d+\s*,\s*)*\d*/
        @trip.invite_users_with_facebook_ids params[:users].split(',')
      end
      flash[:success] = 'All invitations sent.'
      redirect_to trip_path(@trip)
    else
      @pals = @trip.pals_of current_user
      render :layout => false if request.xhr?
    end
  end

  # invited user rejected the invitation
  def reject
    unless @trip = Trip.find_by_id(params[:id])
      redirect_to '/404.html'
      return
    end
    flash[:success] = 'Invitation was rejected'
    @trip.invitees.delete(current_user)
    redirect_to trip_path(@trip)
  end

  # invited user accepted the invitation
  def accept
    unless @trip = Trip.find_by_id(params[:id])
      redirect_to '/404.html'
      return
    end
    @trip.users << current_user
    @trip.invitees.delete(current_user)
    flash[:success] = 'Now you are in this group'
    redirect_to trip_path(@trip)
  end

  # user sent request to join the trip
  def join
    unless @trip = Trip.find_by_id(params[:id])
      redirect_to '/404.html'
      return
    end
    flash[:success] = 'Your request was sent'
    @trip.save_request(current_user)
    redirect_to trip_path(@trip)
  end

  # trip member accepted user who sent the request
  def accept_user
    unless @trip = current_user.trips.find(params[:trip_id])
      redirect_to '/404.html'
      return
    end
    if user = User.find_by_facebook_id(params[:id])
      @trip.users << user
      @trip.waitings.delete(user)
      flash[:success] = 'User was accepted in this group'
    else
      flash[:error] = 'No such user to accept'
    end
    flash[:anchor] = 'requests' if @trip.waitings.any?
    redirect_to trip_path(@trip)
  end


  # trip member denied user who sent the request
  def deny_user
    unless @trip = current_user.trips.find(params[:trip_id])
      redirect_to '/404.html'
      return
    end
    flash[:success] = 'User was denied'
    @trip.waitings.delete(User.find_by_facebook_id(params[:id]))
    flash[:anchor] = 'requests' if @trip.waitings.any?
    redirect_to trip_path(@trip)
  end


  # trip member leaved the trip
  def leave
    unless @trip = current_user.trips.find(params[:id])
      redirect_to '/404.html'
      return
    end
    flash[:success] = 'You have been removed from trip group'
    @trip.users.delete(current_user)
    redirect_to trip_path(@trip)
  end

protected

  # transform form params to saveable attributes
  def travels_attributes
    @attributes = Hash.new
    cud_countries # special function needed
    params[:preference].values.each_with_index do |dates, i|
      @attributes[i] = dates
      # if user want to remove time preference
      if dates[:id] and dates[:begins].blank? and dates[:ends].blank?
        @attributes[i].merge!(:_destroy => true)
      end
    end
    trip_travels = {:travels_attributes => @attributes}
  end

  # Create|Update|Delete (cud) countries
  def cud_countries
    index = 0
    countries = params[:countries]||[] # countries from form
    existing = @existing_countries # countries from DB
    countries.each  do |code|
      @attributes[index.to_s] = {:country => code.first}
      # rewrite existing country if exists
      if travel = existing.at(index)
        @attributes[index.to_s][:id] = travel.id
      end
      index += 1
    end
    # if more countries is in DB than in form, delete unwanted countries
    while existing.size > index
      travel = existing.at(index)
      @attributes[index.to_s] = {:id => travel.id, :_destroy => true}
      index += 1
    end
  end

end

app/helpers/trips_helper.rb
module TripsHelper
  include CalendarHelper
end

app/views/trips/_form.html.erb
<%= form_tag path, :method => method, :id => 'new_travels' do %>

  <%= hidden_field_tag :map, '', :id => 'map_data' %>

  <% if @error %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <%= @error %>
    </div>
  <% end %>

  <p>
    <%= label_tag 'trip_name', 'Name of the trip' %>
    <%= text_field_tag "trip[name]", @trip.name %>
  </p>
  <p>
    <%= label_tag 'trip_about', 'About the trip' %>
    <%= text_area_tag "trip[about]", @trip.about, :style => 'width:100%;height:4em' %>
  </p>

  <div id="matchwrap" style="float:left">
    <p>When do you plan to go on trip?</p>

    <ol id="preferences">
      <%# 1.times do |index| %>
        <%#= render :partial => '/travels/preference', :locals => {:i => index} %>
      <%# end %>
      <li><span></span>
        <%= text_field_tag "preference[0][begins]", preference_value(0,:begins),
                    :readonly => true, :class => 'date begins',
                    :title => 'Departure' %>
        <%= text_field_tag "preference[0][ends]", preference_value(0,:ends),
                    :readonly => true, :class => 'date ends',
                    :title => 'Return' %>
        <%= hidden_field_tag "preference[0][id]", @preferences[0] ? @preferences[0].id : nil %>
        <i class="icon-remove"></i>
      </li>
    </ol>

  </div>

  <div class="out"></div>

  <p><%=t 'new_travel_map_hint' %></p>

  <ul id="countries" style="height:350px">
  <% Country.list.each_pair do |continent, countries| %>
    <li>
      <%= label_tag continent, :class => "continent #{continent_checked(continent)}" do %>
        <%= continent %>
      <% end %>
      <ul style="display:none">
      <% countries.each_pair do |country, code| %>
        <li>
          <%= label_tag country, :class => 'checkbox' do %>
            <%= check_box_tag "countries[#{code}]", code,
                              country_checked(code) %>
            <%= country %>
          <% end %>
        </li>
      <% end %>
      </ul>
    </li>
  <% end %>
  </ul>

  <div id="atlas" class="new-travels"></div>

  <div class="out"></div>

  <%= submit_tag 'Save this trip', :class => 'btn btn-success' %>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    initMap([<%= countries_for_javascript_array %>]);
  });
</script>

app/views/trips/edit.html.erb
<h1>Update travel preferences of the trip</h1>

<p><%=t 'new_travel_map_hint' %></p>

<%= render :partial => 'form', :locals => {
            :path => trips_path, :method => :post } %>

app/views/trips/invite_friends.html.erb
<%= form_tag invite_users_trip_path(@trip), :method => :post, :class => 'formtastic', :id=>"invite_users" do %>
  <div id="user_settings_head">
    <h1>Select friends and invite them</h1>
  </div>
  <div id="select_friends_body">
  </div>
  <div id="user_settings_foot">
    <%= submit_tag 'Invite friends', :class => 'btn btn-success' %>
    <%= submit_tag 'Cancel', {
        :name => 'reset', :class => 'btn', :type => "reset",
        :onclick => "jQuery(document).trigger('close.facebox');" } %>
  </div>
  <textarea class="dis" name="users"></textarea>
<% end %>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<%= javascript_include_tag "jquery.facebook-multifriend-select" %>
<script type="text/javascript">
  $("#select_friends_body").jfmfs(
    {
        friend_fields: "id,name,last_name",
        pre_selected_friends: [],
        exclude_friends: [<%= @pals.collect {|u|u.uid}.join(",") %>]
    }
  );
  $("#select_friends_body").bind("jfmfs.selection.changed", function(e, data) {
    var selectedFriends = $("#select_friends_body").data('jfmfs').getSelectedIds();
    $('#invite_users textarea').html(selectedFriends.join(','));
  });
</script>

app/views/trips/new.html.erb
<h1>New trip with friends</h1>

<%= render :partial => 'form', :locals => {
            :path => trips_path, :method => :post } %>

app/views/trips/show.html.erb
<h1>My trip with friends</h1>

<p>
  <% @users.each_with_index do |user, i| %>
  <% break if i >= 5 %>
    <%= link_to image_tag(facebook_large_picture_url(user.facebook_id)),
                user_profile_url(user.facebook_id),
                :class => 'amatch bimg', :title => "#{user.name}" %>
  <% end %>
</p>

<%= image_tag @trip.map, :id => 'map_image' %>

<div class="out"><br/></div>
<% if @user_own_trip %>
  <ul class="nav nav-tabs" id="trip_tabs">
    <li<%= ' class=active' unless @active_tab %>><a href="#wall">Wall</a></li>
    <li<%= ' class=active' if @active_tab == :about %>><a href="#about">About</a></li>
    <li<%= ' class=active' if @active_tab == :calendar %>><a href="#calendar">Calendar</a></li>
    <li<%= ' class=active' if @active_tab == :files %>><a href="#files">Files</a></li>
    <% if @trip.waitings.any? %>
      <li<%= ' class=active' if @active_tab == :requests %>><a href="#requests">Requests</a></li>
    <% end %>
  </ul>
<% end %>

<div class="tab-content">
<div class="tab-pane<%= ' active' unless @active_tab %>" id="wall">
    <h2><%= @trip.name %></h2>
    <% if @country_message %>
      <p>We are going to visit <%= @country_message %>.</p>
    <% end %>
    <br/>

    <% if @user_invited_trip %>
      <strong>You are invited to this trip!</strong>
      <%= link_to('Accept invitation', accept_trip_path(@trip), :class => 'btn btn-success', :method => :put) %>
      <%= link_to('Reject invitation', reject_trip_path(@trip), :class => 'btn btn-danger', :method => :put) %>
    <% elsif not @user_invited_trip and not @user_own_trip and not @user_waiting_trip %>
      <%= link_to('Join the trip', join_trip_path(@trip), :class => 'btn btn-primary', :method => :put) %>
    <% end %>

    <br/><br/>
    <div class="fb-comments" data-href="<%= trip_url(@trip) %>" data-num-posts="5" data-width="400"></div>
</div>

<div class="tab-pane<%= ' active' if @active_tab == :about %>" id="about">
  <% if @user_own_trip %>
    <%= link_to('Invite friends', invite_users_trip_path(@trip), :class => 'btn btn-primary', :rel => 'facebox') %>
    <%= link_to('Leave trip', leave_trip_path(@trip), :class => 'btn btn-primary', :method => :put, :confirm => 'Are you sure?') %>
    <br/><br/>

    <%= render :partial => 'form', :locals => {
             :path => trip_path(@trip), :method => :put } %>
  <% else %>
    <%= image_tag @trip.map %>
  <% end %>
</div>

<div class="tab-pane<%= ' active' if @active_tab == :calendar %>" id="calendar">
  <%= link_to('Add event', new_trip_event_path(@trip), :class => 'btn btn-primary', :rel => 'facebox') if @user_own_trip %><br/><br/>

  <%= raw(event_calendar) %>
</div>

<div class="tab-pane<%= ' active' if @active_tab == :files %>" id="files">
  <%= link_to('Upload files', new_trip_file_path(@trip), :class => 'btn btn-primary', :rel => 'facebox') if @user_own_trip %><br/><br/>

  <% unless @files.blank? %>
    <% @files.each do |file| %>
      <p><%= link_to file.name, file.file.url %> (<%= number_to_human_size file.file_file_size %>, <%= file.file_file_name.split('.').last.upcase %>) <%= link_to image_tag('trash.png'), trip_file_path(@trip.id, file.id), :method => :delete, :confirm => 'Are you sure?', :title => 'Delete file' %></p>
    <% end %>
  <% end %>
</div>

<% if @trip.waitings.any? and @user_own_trip %>
  <div class="tab-pane<%= ' active' if @active_tab == :requests %>" id="requests">
    <% @trip.waitings.each do |user| %>
      <div class="msg">
        <%= image_tag user.picture_url,
                :class => "i#{user.facebook_id} tip",
                :title => user.name, :rel => "/friend/facebook/#{user.facebook_id}" %>
        <div>
          <%= link_to user.name, facebook_profile_url(user.facebook_id), :class=>'name', :target => '_blank'%>
          <%= link_to('Accept', accept_user_trip_path(@trip, user.facebook_id), :class => 'btn btn-success', :method => :put)  %>
          <%= link_to('Deny', deny_user_trip_path(@trip, user.facebook_id), :class => 'btn btn-danger', :method => :put)  %>
        </div>
        <div class="out"></div>
      </div>
      <br/><br/>
    <% end %>
  </div>
<% end %>

</div>