config/routes.rb
Tb::Application.routes.draw do



  resources :travels, :only => [:new, :create] do
    collection do
      get 'match'
    end
  end

  resources :trips, :except => [:destroy, :edit] do
    member do
      get  'invite_friends', :as => 'invite_users'
      post 'invite_friends'
      put  'join'
      put  'leave'
      put  'reject'
      put  'accept'
    end
    resources :files, :except => [:show, :index, :edit, :update]
    resources :events, :except => [:show, :index]
  end
  match '/trips/:id/:year(/:month)' => 'trips#show', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/trips/:trip_id/user/:id/accept' => 'trips#accept_user', :as => :accept_user_trip, :via => :put
  match '/trips/:trip_id/user/:id/deny' => 'trips#deny_user', :as => :deny_user_trip, :via => :put

  root :to => "main#index"

  match "/signin" => "services#signin"
  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      get 'failure'
    end
  end

  match 'user/settings' => 'main#user_settings', :as => 'user_settings'
  match 'user/:uid' => 'main#user_profile', :as => 'user_profile'
  match 'friend/facebook/:uid' => 'facebook#friend_info'
  match 'other-facebook-friends' => 'facebook#not_in_app_friends'

  match 'message/:id' => 'main#message'

  match 'invite_friends' => 'facebook#invite', :as => 'invite_friends'
  match 'share' => 'facebook#share', :as => 'share'

  match 'welcome' => 'facebook#welcome'

end

app/models/travel.rb
# Time or Country preference
class Travel < ActiveRecord::Base
  include CountryNameHelper

  belongs_to :user
  belongs_to :trip

  attr_accessible :country, :begins, :ends, :popularity

  validate :presence_of_country_or_dates
  validates :begins, :date => {:before => :ends }, :if => :dates_present?

  # preference type scopes
  scope :country, where('country is not null')
  scope :time,    where('country is null')

  def self.not_user(id)
    where(Travel.arel_table[:user_id].not_eq(id)).where(:trip_id => nil)
  end

  def self.users(ids)
    includes(:user).where(["user_id IN (?)", ids]).where(:trip_id => nil)
  end

  def self.most_popular
    where('popularity is not null').
    order('popularity DESC').limit(AppConfig.most_popular_limit.to_i)
  end

  #
  # matching scopes - for searching within all records
  #

  def self.match_time(begins, ends)
    includes(:user).
    where(['begins <= ? and ends >= ?', ends, begins])
    # see http://c2.com/cgi/wiki?TestIfDateRangesOverlap for explanation
  end

  def self.match_country(code)
    includes(:user).where(:country => code).where(:trip_id => nil)
  end

  def self.match_users_country(travels, ids)
    countries = travels.map {|t| t.country }
    includes(:user).
    users(ids).
    where('country IN (?)', countries).
    where(:trip_id => nil)
  end

  def self.match_users_time(travels, ids)
    user_scope = includes(:user).users(ids)
    travels.map {|t|
      user_scope.where(['begins <= ? and ends >= ?', t.ends, t.begins]).where(:trip_id => nil)
    }.flatten
  end


  #
  # matching methods - searchs what matches for one object
  # = call matching scopes with object parameters
  #

  def match_time(ids)
    Travel.users(ids).match_time(self.begins, self.ends)
  end

  def match_country(ids)
    Travel.users(ids).match_country(self.country)
  end

  def self.users_countries(user_ids)
    users_countries_hash = {}
    select('user_id, country').country.
    where(["user_id in (?)", user_ids]).
    group_by(&:user_id).
    each {|u,t| users_countries_hash[u] = t.map(&:country).join(' ') }
    users_countries_hash
  rescue
    {}
  end

  # access helper
  def countryname
    country_name self.country||''
  end

  def date_range
    "#{I18n.l self.begins} - #{I18n.l self.ends}"
  end

  # date setters - save in right format
  def begins=(date)
    date = if date.blank?
      nil
    else
      Date.strptime(date, I18n.t("date.formats.default"))
    end
    super(date)
  end

  def ends=(date)
    date = if date.blank?
      nil
    else
      Date.strptime(date, I18n.t("date.formats.default"))
    end
    super(date)
  end

private

  # validation method
  def presence_of_country_or_dates
    if [self.country, self.begins, self.ends].compact.size == 0
      self.errors[:base] << "No travel preference filled"
    end
  end

  # condition for date validation - both of dates must be given
  def dates_present?
    [self.begins, self.ends].compact.size > 0
  end

end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  include CountryNameHelper

  before_filter :authenticate_user!

  # My Travel Preferences form
  def new
    @countries   = []
    @preferences = []
    # load travel preferences and show them
    current_user.travels.each do |travel|
      if travel.country.blank?
        @preferences.push travel
      else
        @countries.push travel.country
      end
    end
  end

  # My Travel Preferences - process form - POST data
  def create
    @existing_countries = current_user.travels.country
    # save update User with travel_attributes (helper method below)
    if current_user.update_attributes(travels_attributes)
      current_user.map = params[:map] # make map from svg data
      current_user.create_messages
      new_countries = @country_codes - @existing_countries.map {|t| t.country }
      current_user.notify_perfect_matches new_countries
      flash[:success] = t('create_travel_success')
      flash[:from_travel_create] = true
      redirect_to :action => 'match'
    else
      # invalid attributes - transform them to show
      @countries = params[:countries].collect {|c|c.first}||[]
      @preferences = params[:preference].values.map do |preference|
        OpenStruct.new(preference) # hash with method-like access
      end
      # TODO better errors report
      @error = t('create_travel_error')
      render :action => 'new'
    end
  end


  def match
    @preferences = []
    countries = []
    current_user.travels.each do |travel|
      if travel.country
        countries << travel.country
      else
        @preferences << travel
      end
    end
    @preferences = @current_user.travels.time
    @country_matches = @current_user.match(:country)
    @time_matches = @current_user.match(:time)
    @time_messages = @current_user.match_messages(
      :time,    @time_matches,    :include_country_messages => true
    )
    @country_messages = @current_user.match_messages(
      :country, @country_matches, :include_time_messages    => true
    )
    # use loaded matches, so no more database request required (RE-USE)
    @perfects = @current_user.perfect_matches(@time_matches,@country_matches)

    @checkins = @current_user.matched_friends_checkins(countries)
    @photos   = @current_user.matched_friends_photos(countries)

    @country_heat = Hash.new(0)

    @country_matches.each do |travel|
      @country_heat[travel.country] += 1
    end
    @friends_locations = @current_user.facebook_friends_locations(countries)
    @friends_locations.each do |friends_location|
      friends_location[1].values.each do |location|
        @country_heat[location[1]] += 1 # location = [ country_name, country_code ]
      end
    end

    @photos.values.each do |countries_posts|
      countries_posts.keys.each do |country|
        @country_heat[country] += 1
      end
    end

    @time_heat = Hash.new(0)
    # we use loop in view /travels/match for performance reason
  end

private

  # transform form params to saveable attributes
  def travels_attributes
    @attributes = Hash.new
    cud_countries # special function needed
    params[:preference].values.each_with_index do |dates, i|
      @attributes[i] = dates
      # if user want to remove time preference
      if dates[:id] and dates[:begins].blank? and dates[:ends].blank?
        @attributes[i].merge!(:_destroy => true)
      end
    end
    user_travels = {:travels_attributes => @attributes}
  end

  # Create|Update|Delete (cud) countries
  def cud_countries
    index = 0
    countries = params[:countries]||[] # countries from form
    existing = @existing_countries # countries from DB
    @country_codes = []
    popularity = compute_country_travels_popularity
    countries.each  do |code|
      @attributes[index.to_s] = {:country => code.first}
      @country_codes << code.first
      # rewrite existing country if exists
      if travel = existing.at(index)
        @attributes[index.to_s][:id] = travel.id
      end
      @attributes[index.to_s][:popularity] = popularity[code.first]||0
      index += 1
    end
    # if more countries is in DB than in form, delete unwanted countries
    while existing.size > index
      travel = existing.at(index)
      @attributes[index.to_s] = {:id => travel.id, :_destroy => true}
      index += 1
    end
  end

  def compute_country_travels_popularity
    popularity = Hash.new(0) # init hash with zeros
    # get all countries of all friends and make histogram
    Travel.users(current_user.friend_ids).country.each do |travel|
      popularity[travel.country] += 1
    end
    popularity
  end

end

app/helpers/travels_helper.rb
module TravelsHelper
  include CountryNameHelper
  include PostsHelper

  # do time preference value if there is
  def preference_value(index, date)
    I18n.l @preferences[index].send(date)
  rescue
    begin
      @preferences[index].send(date)||''
    rescue
      nil
    end
  end

  # time match preference helper
  def preference_options
    html = '<option value="-"></option>'
    @preferences.each_with_index do |p, i|
      html << content_tag(
        :option,"#{(i+1).ordinalize} preference",:value=>"#{p.begins}_#{p.ends}"
      )
    end
    html.html_safe
  end

  # check if continent will be checked
  def continent_checked(name)
    params[:continents].include?(name) ? 'expanded' : 'collapsed'
  rescue
    ''
  end

  # check if country will be checked
  def country_checked(code)
    @countries.include? code
  rescue
    false
  end

  # print inner of JS array for map init
  def countries_for_javascript_array
    @countries.collect {|c| "'#{c}'" }.join(',').html_safe
  rescue
    ''
  end

  # JS array with countries
  def country_matches_for_javascript_array
    @country_matches.collect {|c| "'#{c.country}'" }.uniq.join(',').html_safe
  rescue
    ''
  end

  # JS array with time prefs
  def time_matches_for_js_array(array)
    array.uniq.map {|c|"'#{c}'"}.join(',').html_safe
  rescue
    ''
  end

  def time_message(dtext, ctext)
    message = "also wants to travel #{dtext}"
    message = "#{message}, but wants to go to #{ctext}" unless ctext.blank?
    "#{message}."
  end

  def country_message(ctext, dtext)
    message = "also wants to go to #{ctext}"
    message = "#{message}, but wants to travel #{dtext}" unless dtext.blank?
    "#{message}."
  end

end

app/views/travels/_aggregated_match.html.erb
<span class="amatch">
    <%= link_to image_tag(facebook_large_picture_url(user.facebook_id),
                :title => "#{user.name} #{strip_tags(message)}"),
                user_profile_url(user.facebook_id), :class=>'bimg' %>
    <%= link_to user.name,
                user_profile_url(user.facebook_id), :class=>'name' %>
</span>

app/views/travels/_match.html.erb
<div class="match<%= " #{special}" if special %>">
  <%= image_tag user.picture_url,
                :class => "i#{user.facebook_id} tip",
                :title => user.name,
                :rel => "/friend/facebook/#{user.facebook_id}" %>
  <div>
    <%= link_to user.name, user_profile_url(user.facebook_id),
                :class=>'name', :target => '_blank' %>
    <%= message.html_safe %>

  </div>
  <div class="out"></div>
</div>

app/views/travels/_preference.html.erb
<li><span><%= (i+1).ordinalize %> preference</span>
  <%= text_field_tag "preference[#{i}][begins]", preference_value(i,:begins),
                    :readonly => true, :class => 'date begins',
                    :title => t('earliest_departure') %>
  <%= text_field_tag "preference[#{i}][ends]", preference_value(i,:ends),
                    :readonly => true, :class => 'date ends',
                    :title => t('latest_return') %>
  <%= hidden_field_tag "preference[#{i}][id]",
                        @preferences[i] ? @preferences[i].id : nil %>
  <i class="icon-remove"></i>
</li>

app/views/travels/_travel_fields.html.erb
  <%= f.input :country, :as => :hidden %>
  <%= f.input :begins,  :as => :string, :input_html => { :class => 'date' },
                        :label => false %>
  <%= f.input :ends,    :as => :string, :input_html => { :class => 'date' },
                        :label => false %>
  <%#= link_to_remove_association 'Remove travel', f, :title => 'Remove this travel' %>

app/views/travels/create.html.erb
<%= render :partial => '/shared/facebook_wall_post_form' %>

app/views/travels/match.html.erb
<% if flash[:success] and flash[:from_travel_create] %>
  <script type="text/javascript">
  $(document).ready(function() {
    jQuery.facebox({ ajax: '<%= share_path %>' });
    /*$(document).bind('afterClose.facebox', function() {
      window.location = '<%= match_travels_path %>';
      window.location.href = '<%= match_travels_path %>';
    });*/
  });
  </script>
<% end %>

<br/>

<ul id="countries" style="height:340px">
  <% Country.list.each_pair do |continent, countries| %>
    <li class="continents" style="display:none">
      <%= continent %>
      <ul>
      <% countries.each_pair do |country, code| %>
        <li style="display:none" id="countries_<%= code %>"><%= country %></li>
      <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<div id="atlas" class="country_matches"></div>
<div id="legend" class="tar">
  <img src="/img/heat.png" alt="Map legend" /><br/>
  <small>more friends</small> &rarr;
</div>




<div id="perfects" class="out">
<% if @perfects.any? %>
  <h1>Perfect travel matches</h1>
  <% @perfects.each_pair do |friend, travels| %>
  <div class="match">
    <%= image_tag friend.picture_url,
                :class => "i#{friend.facebook_id} tip",
                :title => friend.name,
                :rel => "/friend/facebook/#{friend.facebook_id}" %>
    <div>
      <%= link_to friend.name,facebook_profile_url(friend.facebook_id), :target => '_blank' %>
      also wants to go to
      <%= friend.messages_country(travels[:country]).first.html_safe %>
      and also wants to travel
      <%= friend.messages_time(travels[:time]).first.html_safe %>

      <%#= travels[:country].map {|c| c.countryname }.join(' or ')
      %>
      <%#= travels[:time].map {|c| c.date_range }.join(' or ')
      %>
    </div>
    <div class="out"></div>
  </div>
  <% end %>
<% end %>
</div>


<ul id="matchtabs" class="nav nav-tabs">
  <li><a href="#country_matches" data-toggle="tab">Search by Destination</a></li>
  <li><a href="#time_matches" data-toggle="tab">Search by Schedule</a></li>
</ul>


<div id="preferences" class="matching">
    <%= text_field_tag "begins", '',
                      :readonly => true, :class => 'date',
                    :title => t('earliest_departure') %>
    <%= text_field_tag "ends", '',
                      :readonly => true, :class => 'date',
                    :title => t('latest_return') %>
    <%= select_tag 'preference_choice', preference_options %>
</div>


<div id="matchwrap" class="tab-content">


  <div id="time_matches" class="tab-pane">
  <%=t 'time_match_message' %>
  <% if @time_messages.any? %>
    <% time_match_countries = [] %>
    <% @time_messages.each do |user, content| %>
      <% # should be in controller but performance :) %>
      <% content[2].each {|country| @time_heat[country] += 1 } %>
      <%= render :partial => 'match', :locals => {
          :user    => user,
          :message => time_message(content.first, content[3]),
          :special => [content[1], content[2].join(' ')].join(' ')
      } %>
      <% time_match_countries += content[2] %>
    <% end %>
  <% end %>
  </div>


  <div id="country_matches" class="tab-pane">
  <%=t 'country_match_message' %>

    <p><%=t 'match_map_hint' %></p>


  <% grouped_matches = @country_matches.group_by(&:country) %>
  <% shown_users = [] %>
  <% grouped_matches.each do |country, travels| %>
    <% if travels.count <= AppConfig.shown_without_aggregation %>
      <% travels.each do |travel| %>
        <% next if shown_users.include?(travel.user_id) %>
        <% shown_users << travel.user_id %>
        <% content = @country_messages[travel.user] %>
        <%= render :partial => 'match', :locals => {
            :user    => travel.user,
            :message => country_message(content.first, content[2]),
            :special => content[1] # countries string to class
        } %>
      <% end %>
    <% else # show aggregation %>
      <div class="match <%= country %>">
        <span><%= travels.count %> of your friends want to go to <%= country_name(country) %></span>
        <div class="grouped"><div class="items">
          <% travels.group_by(&:user_id).values.each do |user_travels| %>
            <% content = @country_messages[user_travels.first.user] %>
            <%= render :partial => 'aggregated_match', :locals => {
                :user    => user_travels.first.user,
                :message => country_message(content.first, content[2]),
                :special => content[1] # countries string to class
            } %>
          <% end %>
        </div></div>
        <a href="#" class="prev browse left" onclick="return false;"></a>
        <a href="#" class="browse next right" onclick="return false;"></a>
        <div class="out"></div>
      </div>
    <% end %>
  <% end %>

  <% if @photos.any? %>
    <% @photos.each do |friend, countries_photos| %>
      <%
        skip = []
        if @friends_locations.any? and @friends_locations[friend]
          skip << @friends_locations[friend][:current][1] if @friends_locations[friend].key?(:current)
          skip << @friends_locations[friend][:hometown][1] if @friends_locations[friend].key?(:hometown)
        end
      %>
      <% countries_photos.each do |country, photos| %>
        <% next if skip.include?(country) %>
        <div class="match <%= country %>">
          <%= image_tag friend.picture_url,
                      :class => "i#{friend.facebook_id} tip",
                      :title => friend.name,
                      :rel => "/friend/facebook/#{friend.facebook_id}" %>
          <div>
            <%= link_to friend.name, user_profile_url(friend.facebook_id), :class=>'name' %>
            <%  message = 'was in '
                message << country_name(country)
            %>
            <%= message.html_safe %>
            <%= scrollable_photos(photos).html_safe %>
          </div>
          <div class="out"></div>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <% if @friends_locations.any? %>
    <div id="locations">
    <% @friends_locations.each do |friend, location| %>
      <div class="match <%=location.values.map {|v|v[1]}.join(' ') %>">
        <%= image_tag friend.picture_url,
                      :class => "i#{friend.facebook_id} tip",
                      :title => friend.name,
                      :rel => "/friend/facebook/#{friend.facebook_id}" %>
        <div class="<%= location.keys.join(' ') %>">
          <%= link_to friend.name, user_profile_url(friend.facebook_id), :class=>'name' %>
          <%  messages = []
              if location.key?(:current)
                messages << "lives in #{location[:current][0]}"
              end
              if location.key?(:hometown)
                messages << "is from #{location[:hometown][0]}"
              end
          %>
          <%= messages.join(' and ') %>
        </div>
        <div class="out"></div>
      </div>
    <% end %>
    </div>
  <% end %>

  <% if @checkins.any? %>
    <% @checkins.each do |checkin| %>
      <div class="match <%= checkin.country %>">
        <% friend = checkin.user %>
        <%= image_tag friend.picture_url,
                      :class => "i#{friend.facebook_id} tip",
                      :title => friend.name,
                      :rel => "/friend/facebook/#{friend.facebook_id}" %>
        <div>
          <%= link_to friend.name, facebook_profile_url(friend.facebook_id), :class=>'name' %>
          <%  message = 'checked in '
              message << "#{checkin.city}, " if checkin.city
              message << country_name(checkin.country)
              message << " in #{l checkin.created_time}"
              if checkin.message
                message << " with this message: #{checkin.message}"
              end
          %>
          <%= message %>
        </div>
        <div class="out"></div>
      </div>
    <% end %>
  <% end %>

  </div>


</div>

<div class="out"></div>

<script type="text/javascript">
  $(document).ready(function() {

    initMap([]);

    heat_country = {<%= heatmap_javascript_array(@country_heat) %>}
    heat_time = {<%= heatmap_javascript_array(@time_heat) %>}

    selected_country = selected;
    selected_time = [<%= time_matches_for_js_array time_match_countries %>];

    $('.nav-tabs a:first').tab('show');

    initScrollable('.grouped', 5);

  });
</script>

app/views/travels/new.html.erb
<% if flash[:success] and flash[:from_travel_create] %>
  <script type="text/javascript">
  $(document).ready(function() {
    jQuery.facebox({ ajax: '<%= share_path %>' });
    $(document).bind('afterClose.facebox', function() {
      window.location = '<%= match_travels_path %>';
      window.location.href = '<%= match_travels_path %>';
    });
  });
  </script>
<% end %>

<h1>My travel preferences</h1>

<p><%=t 'new_travel_map_hint' %></p>

<%= form_tag travels_path, :method => :post, :id => 'new_travels' do %>

  <%= hidden_field_tag :map, '', :id => 'map_data' %>

  <ul id="countries">
  <% Country.list.each_pair do |continent, countries| %>
    <li>
      <%= label_tag continent, :class => "continent #{continent_checked(continent)}" do %>
        <%= continent %>
      <% end %>
      <ul style="display:none">
      <% countries.each_pair do |country, code| %>
        <li>
          <%= label_tag country, :class => 'checkbox' do %>
            <%= check_box_tag "countries[#{code}]", code,
                              country_checked(code) %>
            <%= country %>
          <% end %>
        </li>
      <% end %>
      </ul>
    </li>
  <% end %>
  </ul>

  <div id="atlas" class="new-travels"></div>

<div id="matchwrap">

  <p>When do you want to travel?</p>

  <ol id="preferences">
    <% 3.times do |index| %>
      <%= render :partial => 'preference', :locals => {:i => index} %>
    <% end %>
  </ol>

  <% if @error %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <%= @error %>
    </div>
  <% end %>

  <%= submit_tag 'Save & Find travel buddies', :class => 'btn btn-success' %>

</div>
  <div class="out"></div>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    initMap([<%= countries_for_javascript_array %>]);
  });
</script>