config/routes.rb
Tb::Application.routes.draw do



  resources :travels, :only => [:new, :create] do
    collection do
      get 'match'
    end
  end

  resources :trips, :except => [:destroy, :edit] do
    member do
      get  'invite_friends', :as => 'invite_users'
      post 'invite_friends'
      put  'join'
      put  'leave'
      put  'reject'
      put  'accept'
    end
    resources :files, :except => [:show, :index, :edit, :update]
    resources :events, :except => [:show, :index]
  end
  match '/trips/:id/:year(/:month)' => 'trips#show', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/trips/:trip_id/user/:id/accept' => 'trips#accept_user', :as => :accept_user_trip, :via => :put
  match '/trips/:trip_id/user/:id/deny' => 'trips#deny_user', :as => :deny_user_trip, :via => :put

  root :to => "main#index"

  match "/signin" => "services#signin"
  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      get 'failure'
    end
  end

  match 'user/settings' => 'main#user_settings', :as => 'user_settings'
  match 'user/:uid' => 'main#user_profile', :as => 'user_profile'
  match 'friend/facebook/:uid' => 'facebook#friend_info'
  match 'other-facebook-friends' => 'facebook#not_in_app_friends'

  match 'message/:id' => 'main#message'

  match 'invite_friends' => 'facebook#invite', :as => 'invite_friends'
  match 'share' => 'facebook#share', :as => 'share'

  match 'welcome' => 'facebook#welcome'

end

app/controllers/files_controller.rb
class FilesController < ApplicationController

  before_filter :authenticate_user!


  def new
    @trip = current_user.trips.find(params[:trip_id])
    @attachment = @trip.attachments.build
    render :layout => false if request.xhr?
  end

  def create
    @trip = current_user.trips.find(params[:trip_id])
    if params[:attachment][:name].blank? and params[:attachment][:file]
      params[:attachment][:name] = params[:attachment][:file].original_filename
    end
    @attachment = @trip.attachments.new(params[:attachment])

    if @attachment.save
      flash[:success] = 'File was successfully uploaded.'
    else
      flash[:error] = 'File upload failed. ' + @attachment.errors.full_messages.join('. ')
    end
    flash[:anchor] = 'files'
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip = current_user.trips.find(params[:trip_id])
    @attachment = @trip.attachments.find(params[:id])
    @attachment.destroy
    flash[:notice] = 'File was successfully deleted'
    flash[:anchor] = 'files'
    redirect_to trip_path(@trip)
  end

end

app/views/files/new.html.erb
<%= semantic_form_for @attachment, :url => (@attachment.id ? trip_file_path(@trip, @attachment) : trip_files_path(@trip)) do |f| %>
<div id="user_settings_head">
  <h1><%=t 'attachment_form_title' %></h1>
</div>
<div id="user_settings_body">
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :file, :as => :file %>
  <% end %>
</div>
<div id="user_settings_foot">
    <% if @attachment.id %>
      <small style="float:left">
        <%= link_to 'Delete', trip_file_path(@trip.id, @attachment.id), :method => :delete, :confirm => 'Are you sure?' %>
      </small>
    <% end %>
    <%= submit_tag 'Save', :class => 'btn btn-success' %>
    <%= submit_tag 'Cancel', {
        :name => 'reset', :class => 'btn', :type => "reset",
        :onclick => "jQuery(document).trigger('close.facebox');" } %>
</div>
<% end %>